server:
  port: ${PORT:11008}
spring:
  application:
    name : tracing
  cloud:
    config:
      uri: http://config:8888
      fail-fast: true
      password: ${CONFIG_SERVICE_PASSWORD}
      username: user