node {
    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/MadeInChina/PiggyMetrics.git', credentialsId: 'github-slam', branch: 'Finchley.BUILD-SNAPSHOT'
        }

        stage('Build') {
           dir ('core-services/statistics-service') {
                sh 'mvn clean install'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
            }
        }

        stage('Image Build And Publish') {
            dir ('core-services/statistics-service') {
                 def app =  docker.build "slamhan/piggymetrics-statistics-service:2.0.2.RELEASE"
                 app.push()
            }
        }

    }

}