version: '3'
services:
  statistics-service:
    image: registry.homelab.org/piggymetrics-statistics-service:2.3.0.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
      STATISTICS_SERVICE_PASSWORD: password
    networks:
      - default
  notification-service:
    image: registry.homelab.org/piggymetrics-notification-service:2.3.0.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
      NOTIFICATION_SERVICE_PASSWORD: password
    networks:
      - default
  auth-service:
    image: registry.homelab.org/piggymetrics-auth-service:2.3.0.RELEASE
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
      NOTIFICATION_SERVICE_PASSWORD: password
      STATISTICS_SERVICE_PASSWORD: password
    networks:
      - default
  statistics-mongodb:
    image: registry.homelab.org/piggymetrics-mongodb:2.3.0.RELEASE
    environment:
      MONGODB_PASSWORD: password
    networks:
      - default
  account-service:
    image: registry.homelab.org/piggymetrics-account-service:2.3.0.RELEASE
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
    networks:
      - default
networks:
 default:
    external:
      name: piggynet