node {
    // Setup the Docker Registry (Docker Hub) + Credentials
    registry_url = "https://index.docker.io/v1/" // Docker Hub
    docker_creds_id = "slam-docker-hub" // name of the Jenkins Credentials ID

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/MadeInChina/PiggyMetrics.git', credentialsId: 'github-slam', branch: 'master'
        }

        stage('Build') {
           dir ('monitoring-server') {
                sh 'mvn clean install'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
            }
        }

        stage('Image Build And Publish') {
            dir ('monitoring-server') {
                docker.withRegistry("${registry_url}", "${docker_creds_id}") {
                     def app =  docker.build "slamhan/piggymetrics-monitoring-server:latest"
                     app.push()
                }
            }
        }

        stage ('Upgrade') {
            dir ('monitoring-server') {
            sh 'rancher-compose --url http://192.168.2.34:8888/v2-beta/projects/1a5  --access-key 602311D6074EC0DFCBB5 --secret-key YttmUwex7ryzBLnM1CctyumSqac16AboL43Va8df -f ../docker-compose-on-rancher-ui.yml -p Applications up monitoring-server --force-upgrade -p -c -d'
            }
        }
    }

}