apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: config
  name: config
  namespace: piggmetrics
spec:
  selector:
    io.kompose.service: config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: config
  name: config
  namespace: piggmetrics
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.kompose.service: config
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
          image: registry.docker.com/piggymetrics-config:2.3.0.RELEASE
          name: registry
          ports:
            - containerPort: 8888
              hostPort: 8888
              name: 8888tcp8888
              protocol: TCP

      restartPolicy: Always