apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: config
  name: config
  namespace: piggmetrics
spec:
  type: ClusterIP
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    io.kompose.service: config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: config
  name: config
  namespace: piggmetrics
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.kompose.service: config
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
          image: slamhan/piggymetrics-config:2.0.4-SNAPSHOT
          name: registry
          ports:
            - containerPort: 8888
      restartPolicy: Always