version: '2'
services:
  turbine:
    image: slamhan/piggymetrics-turbine:2.0.1.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 8300:8080/tcp
    networks:
      - piggynet
  registry:
    image: slamhan/piggymetrics-registry:2.0.4-SNAPSHOT
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 8761:8761/tcp
    networks:
      - piggynet
  tracing:
    image: openzipkin/zipkin
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
    stdin_open: true
    tty: true
    ports:
      - 9411:9411/tcp
    networks:
      - piggynet
  auth-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.4-SNAPSHOT
    environment:
      MONGODB_PASSWORD: password
    networks:
      - piggynet
  account-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.4-SNAPSHOT
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: password
    networks:
      - piggynet
  monitoring:
    image: slamhan/piggymetrics-monitoring:2.0.4-SNAPSHOT
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
    - 9000:8080/tcp
    networks:
    - piggynet
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15672:15672/tcp
    - 5672:5672/tcp
    networks:
    - piggynet
  statistics-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.4-SNAPSHOT
    environment:
      MONGODB_PASSWORD: password
    networks:
    - piggynet
  notification-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.4-SNAPSHOT
    environment:
      MONGODB_PASSWORD: password
    networks:
    - piggynet
  config:
    image: slamhan/piggymetrics-config:2.0.4-SNAPSHOT
    environment:
      CONFIG_SERVICE_PASSWORD: password
    networks:
      - piggynet
  gateway:
    image: slamhan/piggymetrics-gateway:2.0.4-SNAPSHOT
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
    - 4000:4000/tcp
    networks:
    - piggynet
networks:
  piggynet: