apiVersion: v1
kind: Service
metadata:
  labels:
    name: registry
  name: registry
  namespace: piggmetrics
spec:
  type: ClusterIP
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    io.kompose.service: registry