pipeline {
    agent any

    tools {
            maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                dir ('infrastructure-services/admin') {
                   sh 'mvn clean install'
                }
            }
        }
        stage('Image Build And Push') {
            steps {
                dir ('infrastructure-services/admin') {
                    withDockerRegistry([credentialsId: "slamhan-dockerhub-repo", url: ""]) {
                        script {
                            def app = docker.build 'registry.homelab.org/piggymetrics-admin:2.3.0.RELEASE'
                            app.push()
                        }
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir ('infrastructure-services/admin/yaml/deployment') {
                    withKubeConfig(credentialsId: 'kube-local-test.config') {
                        sh 'kubectl apply -f admin-deployment.yaml'
                    }
                }
            }
        }
    }
}