pipeline {
    agent any

    tools {
            maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                dir ('infrastructure-services/turbine') {
                   sh 'mvn clean install'
                }
            }
        }
        stage('Image Build And Push') {
            steps {
                dir ('infrastructure-services/turbine') {
                    script {
                        def app = docker.build "slamhan/piggymetrics-turbine:2.0.3.RELEASE"
                        app.push()
                    }
                }
            }
        }
    }
}