apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: config
  name: config
  namespace: piggmetrics
spec:
  type: ClusterIP
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    io.kompose.service: config