pipeline {
    agent any

    tools {
        maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                dir('infrastructure-services/registry') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Image Build And Push') {
            steps {
                dir('infrastructure-services/registry') {
                    withDockerRegistry([credentialsId: "slamhan-dockerhub-repo", url: ""]) {
                        script {
                            def app = docker.build 'registry.docker.com/piggymetrics-registry:2.3.0.RELEASE'
                            app.push()
                        }
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                dir('infrastructure-services/registry/yaml/deployment') {
                    withKubeConfig(credentialsId: 'kube-local-test.config') {
                        sh 'kubectl apply -f registry-deployment.yaml'
                    }
                }
            }
        }
    }
}