apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: admin
  name: admin
  namespace: piggmetrics
spec:
  selector:
    io.kompose.service: admin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin
  name: admin
  namespace: piggmetrics
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.kompose.service: admin
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
          image: registry.homelab.org/piggymetrics-admin:2.3.0.RELEASE
          name: registry
          ports:
            - containerPort: 8080
              hostPort: 8200
              name: 8080tcp82000
              protocol: TCP
      restartPolicy: Always