apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: registry
  name: registry
  namespace: piggmetrics
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: registry
  name: registry
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.kompose.service: registry
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
          image: slamhan/piggymetrics-registry:2.0.4-SNAPSHOT
          name: registry
          ports:
            - containerPort: 8761
      restartPolicy: Always