apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: piggmetrics
  labels:
    name: registry
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: registry
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
          name: registry
          image: slamhan/piggymetrics-registry:2.0.4-SNAPSHOT
          imagePullPolicy: IfNotPresent
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8888
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 1000Mi