security:
  oauth2:
    client:
      client-id: account-service
      client-secret: ${ACCOUNT_SERVICE_PASSWORD}
      access-token-uri: http://auth-service:5000/uaa/oauth/token
      access-token-validity-seconds: 3600
      refresh-token-validity-seconds: 3600
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /accounts
  port: 6000

#logging:
#  level:
#    org.springframework.security: DEBUG