spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000

security:
  oauth2:
    resource:

#logging:
#  level:
#    org.springframework.security: DEBUG
