apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
  namespace: piggmetrics
spec:
  selector:
    io.kompose.service: gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway
  name: gateway
  namespace: piggmetrics
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICE_PASSWORD
              value: password
          image: registry.docker.com/piggymetrics-gateway:2.3.0.RELEASE
          name: registry
          ports:
            - containerPort: 4000
              hostPort: 4000
              name: 4000tcp4000
              protocol: TCP

      restartPolicy: Always