node {
    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/MadeInChina/PiggyMetrics.git', credentialsId: 'github-slam', branch: 'Finchley.BUILD-SNAPSHOT'
        }

        stage('Image Build And Publish') {
            dir ('infrastructure-services/mongodb') {
                 def app =  docker.build "slamhan/piggymetrics-mongodb:2.0.2.RELEASE"
                 app.push()
            }
        }

    }

}