pipeline {
    agent any

    tools {
            maven 'maven'
    }
    stages {
        stage('Image Build And Push') {
            steps {
                dir ('infrastructure-services/mongodb') {
                    script {
                        def app = docker.build 'registry.docker.com/piggymetrics-mongodb:2.3.0.RELEASE'
                        app.push()
                    }
                }
            }
        }
    }
}