pipeline {
    agent any

    tools {
            maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                dir ('infrastructure-services/monitoring') {
                   sh 'mvn clean install'
                }
            }
        }
        stage('Image Build And Push') {
            steps {
                dir ('infrastructure-services/monitoring') {
                    script {
                        def app = docker.build 'registry.docker.com/piggymetrics-monitoring:2.3.0.RELEASE'
                        app.push()
                    }
                }
            }
        }
    }
}