hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  stream:
      maxConcurrentConnections: 20
      bus:
        enabled: true

turbine:
  combine-host-port: true

eureka:
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} #make the application unique on the rancher service layer
    instance-id: ${spring.cloud.client.ip-address} #make the application unique on the rancher service layer
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current
      filter-order : 3
    
spring:
  application:
    index: ${random.uuid} #make the application unique on the rancher container layer,same service but with multi-instances.
  rabbitmq:
    host: rabbitmq
  zipkin:
    base-url: http://tracing:11008    

feign:
  hystrix:
    enabled: true

logging:
  level:
     org.springframework.cloud.netflix.turbine: DEBUG
     org.springframework.cloud.netflix.hystrix: DEBUG    