turbine:
  combine-host-port: true
#  instanceUrlSuffix: actuator/hystrix.stream

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "info", "hystrix.stream"]

logging:
  level:
     root: INFO
     com.netflix.turbine.monitor: DEBUG