turbine:
#  instanceUrlSuffix:
#    default: actuator/hystrix.stream
  combine-host-port: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    hystrix:
      show-details: always
      stream:
        enabled: true
management:
  endpoints:
    web:
      base-path: /
hystrix:
  metrics:
    enabled: true