node {
    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/MadeInChina/PiggyMetrics.git', credentialsId: 'github-slam', branch: 'master'
        }

        stage('Build') {
           dir ('tracing') {
                sh 'mvn clean install'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
            }
        }

        stage('Image Build And Publish') {
            dir ('tracing') {
                 def app =  docker.build "slamhan/piggymetrics-tracing:latest"
                 app.push()
            }
        }

        stage ('Upgrade') {
            dir ('tracing') {
            sh 'rancher-compose --url http://192.168.2.34:8888/v2-beta/projects/1a5  --access-key 602311D6074EC0DFCBB5 --secret-key YttmUwex7ryzBLnM1CctyumSqac16AboL43Va8df -f ../docker-compose-on-rancher-ui.yml -env-file ../secrets -p Applications up tracing --force-upgrade -p -c -d'
            }
        }
    }

}