version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  fixer:
    image: hakanensari/fixer
    command: unicorn -c config/unicorn.rb
    entrypoint: bin/wait-for-it.sh db:5432 -s --
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
      RACK_ENV: development
      VIRTUAL_HOST: localhost
    ports:
      - 9080:8080/tcp
  scheduler:
    image: hakanensari/fixer
    command: bin/schedule
    entrypoint: bin/wait-for-it.sh db:5432 -s --
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
volumes:
  postgres: