pipeline {
    agent any

    environment {
            REPO_URL = 'https://github.com/MadeInChina/PiggyMetrics.git'
            CREDENTIALS_ID = 'github-slam'
            ENVIRONMENT_ENDPOINT = 'http://192.168.2.34:8888/v2-beta/projects/1a5'
            ACCESS_KEY           = '602311D6074EC0DFCBB5'
            SECRET_KEY           = 'YttmUwex7ryzBLnM1CctyumSqac16AboL43Va8df'
            STACK_NAME           = 'Applications'
            SERVICE_NAME         = 'account-service'
    }

    stages {
        stage('Checkout') {
            steps {
                    echo 'Checking out ...'
                    git branch: 'master', url: env.REPO_URL, credentialsId: env.CREDENTIALS_ID
            }
        }

        stage('Build') {
            steps {
                dir ('account-service') {
                    echo 'Building ...'
                    withMaven(maven: 'maven') {
                        sh 'mvn clean compile'
                    }
                }
            }
        }

        stage('Image Building And Publishing') {
            steps {
                echo 'Image Building And Publishing ...'
                dir ('account-service') {
                    script {
                      docker.build 'slamhan/piggymetrics-account-service:latest'
                   }
                }
            }
        }

        stage ('Upgrade') {
            steps {
                    echo 'Upgrading ...'
                    dir ('account-service') {
                        sh '''
                                rancher-compose --url "$ENVIRONMENT_ENDPOINT"  --access-key "$ACCESS_KEY" --secret-key "$SECRET_KEY" -f ../docker-compose-on-rancher-ui.yml -env-file ../secrets -p "$STACK_NAME" up "$SERVICE_NAME" --force-upgrade -p -c -d
                        '''
                    }
             }
        }
    }
}