version: '2'
services:
##################Testing#####################################
  gatling:
    image: slamhan/piggymetrics-gatling:2.0.3.RELEASE
    environment:
      BASE_URL: http://gateway:4000
      CONCURRENCY: 10
    command: [com.piggymetrics.gatling.AccountServiceSimulation]
    volumes:
      - gatling:/gatling/results
    networks:
      - piggynet
##################Infrastructure Services#####################
  admin:
    image: slamhan/piggymetrics-admin:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 8200:8080/tcp
    networks:
      - piggynet
  turbine:
    image: slamhan/piggymetrics-turbine:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 8300:8080/tcp
    networks:
      - piggynet
  registry:
    image: slamhan/piggymetrics-registry:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 8761:8761/tcp
    networks:
      - piggynet
  tracing:
    image: openzipkin/zipkin
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
    stdin_open: true
    tty: true
    ports:
      - 9411:9411/tcp
    networks:
      - piggynet
  auth-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.3.RELEASE
    environment:
      MONGODB_PASSWORD: password
    networks:
      - piggynet
  account-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.3.RELEASE
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: password
    networks:
      - piggynet
  monitoring:
    image: slamhan/piggymetrics-monitoring:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 9000:8080/tcp
    networks:
      - piggynet
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672/tcp
      - 5672:5672/tcp
    networks:
      - piggynet
  statistics-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.3.RELEASE
    environment:
      MONGODB_PASSWORD: password
    networks:
      - piggynet
  notification-mongodb:
    image: slamhan/piggymetrics-mongodb:2.0.3.RELEASE
    environment:
      MONGODB_PASSWORD: password
    networks:
      - piggynet
  config:
    image: slamhan/piggymetrics-config:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    networks:
      - piggynet
  gateway:
    image: slamhan/piggymetrics-gateway:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
    ports:
      - 4000:4000/tcp
    networks:
      - piggynet
##################Core Services#####################
  statistics-service:
    image: slamhan/piggymetrics-statistics-service:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
      STATISTICS_SERVICE_PASSWORD: password
    external_links:
    - fixer/fixer-api:fixer-api
    networks:
      - piggynet
  notification-service:
    image: slamhan/piggymetrics-notification-service:2.0.3.RELEASE
    environment:
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
      NOTIFICATION_SERVICE_PASSWORD: password
    networks:
      - piggynet
  auth-service:
    image: slamhan/piggymetrics-auth-service:2.0.3.RELEASE
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
      NOTIFICATION_SERVICE_PASSWORD: password
      STATISTICS_SERVICE_PASSWORD: password
    networks:
      - piggynet
  account-service:
    image: slamhan/piggymetrics-account-service:2.0.3.RELEASE
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
      CONFIG_SERVICE_PASSWORD: password
      MONGODB_PASSWORD: password
#     JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y
#    ports:
#      - 8000:8000
    networks:
      - piggynet
#    healthcheck:
#      test: curl -f http://localhost:6000/accounts/actuator/health || exit 1
#      interval: 10s
#      timeout: 60s
networks:
  piggynet:
volumes:
  gatling:
